# Generated by Django 6.0.3 on 2026-03-11 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='active', max_length=20)),
                ('container_id', models.CharField(default='unknown', max_length=64)),
                ('container_name', models.CharField(db_index=True, default='unknown', max_length=255)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_events', models.IntegerField(default=0)),
                ('malicious_events', models.IntegerField(default=0)),
                ('source', models.CharField(default='falco_log', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FalcoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(db_index=True, max_length=255)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('alert', 'Alert'), ('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('notice', 'Notice'), ('informational', 'Informational'), ('debug', 'Debug')], db_index=True, max_length=20)),
                ('output', models.TextField()),
                ('container_id', models.CharField(db_index=True, default='unknown', max_length=64)),
                ('container_name', models.CharField(db_index=True, default='unknown', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('is_malicious', models.BooleanField(db_index=True, default=False)),
                ('malicious_type', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'container_name'], name='monitoring__timesta_b76f77_idx'), models.Index(fields=['is_malicious', '-timestamp'], name='monitoring__is_mali_bb4408_idx')],
            },
        ),
    ]
